# Generated by Django 2.0.7 on 2018-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masterlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('case_nbr', models.IntegerField(blank=True, null=True)),
                ('child_nbr', models.IntegerField(blank=True, null=True)),
                ('child_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=25, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('child_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
