# Generated by Django 2.0.7 on 2018-07-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentMasterlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmasterlist',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parentmasterlist',
            name='sponsorship_start_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
